Upload collection
PEM-Humboldt/stac-data-tools pull request #11
Opened 2024-05-22 13:42 UTC by ManuelStardust

## 🛠️ Changes
- Convert and upload layers
- Upload a collection
- Add utils for manage request to STAC server 
- Add utils for uploads to Blob Storage

## 📝 Associated issues
#10 

## 🤔 Considerations

2024-05-23 22:41 UTC, erikasv requested changes
No alcancé a revisar todo, pero creo que con esos cambios tienes suficiente por ahora

2024-05-23 22:41 UTC, erikasv commented on README.md
> +    - -o --overwrite # Actualiza una colección ya existente (opcional)
Cambia "actualiza" por "sobrescribe", para evitar malos entendidos luego

2024-05-23 22:41 UTC, erikasv commented on src/collection.py
> +                if item.validate():
Será que si el item no pasa la validación se debería abortar todo y arrojar el error?

2024-05-23 22:41 UTC, erikasv commented on src/main.py
> +        abs_config["container"] = getenv("ABS_CONTAINER")
Si se puede, mejor movamos toda la lectura de parámetros a un archivo a aparte como hicimos en el otro repo

2024-05-23 22:41 UTC, erikasv commented on src/collection.py
> +        Check if the collection exists and if going to be overwriter
overwritten

2024-05-23 22:41 UTC, erikasv commented on src/collection.py
> +        self.collection_id = []
Yo creo que esta variable no es necesaria, una vez creado el objeto de pystac de la colección se podría acceder a su id

2024-05-23 22:41 UTC, erikasv commented on src/collection.py
> +        self.items_collection = []
el nombre correcto sería "collection_items". Pero los nombres están muy confusos para entender la diferencia entre ellos, te propongo cambiar `self.collection` por `self.pystac_collection` y `self.items_collection` por `self.pystac_items`, no son los mejores nombres, si se te ocurre otro que nos de a entender que los primeros son los diccionarios para crear los objetos Item de pystac y los segundos son los items ya como objetos de pystac, sería lo mejor

2024-05-23 22:41 UTC, erikasv commented on src/collection.py
> +        self.stac_url = stac_url
otro punto a favor de separar la lectura de parámetros a un archivo, así puedes leer esta variable de ahí en lugar de tener que recibirla

2024-05-28 20:50 UTC, ManuelStardust commented on src/collection.py
> +                if item.validate():
Si, creo que es mejor continuar el proceso y retornar un mensaje para los items que no pudieron ser procesados. Puse el mensaje como una salida de consola, pero podriamos pasarlo a un archivo de log en la carpeta output de la coleccion.

2024-05-28 20:54 UTC, erikasv commented on src/collection.py
> +                if item.validate():
pero lo que yo decía era precisamente lo contrario, si un item falla la validación no sé si deberíamos crear la colección con los que sí la pasaron. Yo creo que no, pero si crees que sí, explica por qué. También @cazapatamar qué opina?

Por otro lado, el cambio que hiciste creo que no aporta nada, porque encerraste el `if` en un `try` y creo que el if en sí mismo no va a generar la excepción.

2024-05-28 21:11 UTC, ManuelStardust commented on src/collection.py
> +                if item.validate():
Perdón, me confundí un poco. Lo deje como estaba porque de esa manera ya esta abortando cuando un item falla la validación. Y pensandolo bien si es mas eficiente atender todos los errores en la creación antes de procesar toda la colección.

2024-05-28 21:15 UTC, erikasv commented on src/collection.py
> +                if item.validate():
seguro que aborta? Yo entiendo que si el item no valida simplemente no lo agrega a `self.stac_items`

2024-05-28 21:41 UTC, ManuelStardust commented on src/collection.py
> +                if item.validate():
Si aborta por las funciones de validación de pystac

2024-05-28 21:44 UTC, cazapatamar commented on src/collection.py
> +                if item.validate():
Creo que por ahora es mejor que si un item falla aborte todo, ya que o si no la coleccion quedaría "a medias". A futuro podriamos incluir funciones para agregar items a una coleccion y que si ya existe entonces que lo actualice y si no que lo cree.

2024-05-30 15:44 UTC, cazapatamar commented on README.md
> +    - -o --overwrite # Sobrescribe una colección ya existente (opcional)
Estaba pensando si quizá sea mejor no recibir este parametro -o y en vez de eso incluir en la lógica un UPSERT. es decir, que si la coleccion no existe la cree y si existe entonces la actualice. Creo que tiene una ventaja (no muy grande) y es facilitar un poco la ejecución del comando para crear o actualizar las colecciones pero al mismo tiempo tiene la desventaja que por error se puede reemplazar toda una colección existente.

No sé si vean que aporte en algo o si no es tan importante @erikasv @ManuelStardust. Podriamos igualmente analizarlo como una mejora a futuro.

2024-05-30 16:15 UTC, erikasv commented on README.md
> +    - -o --overwrite # Sobrescribe una colección ya existente (opcional)
Creo que tuvimos en cuenta esa opción y nos pareció más importante que por defecto sobrescriba y que el investigador que lo use sea consciente de que va a sobrescribir una colección existente.

Porque el otro detalle a tener en cuenta es que no actualiza, sobrescribe, porque la actualización tiene muchas implicaciones que tenemos analizar más detalladamente.

Pero porfa Manuel complementa con lo que vos recordes

2024-05-30 16:52 UTC, erikasv commented on src/config.py
> +from pydantic_settings import BaseSettings, SettingsConfigDict
Por qué el cambio de librería? cuál es la ventaja?

2024-06-06 21:19 UTC, ManuelStardust commented on README.md
> +    - -o --overwrite # Sobrescribe una colección ya existente (opcional)
Si, complementando lo que dice Erika, pienso que de momento nos ayuda a evitar que vivan subiendo colecciones incompletas y por eso lo validamos antes de convertir y cargar capas.

2024-06-06 21:21 UTC, ManuelStardust commented on src/config.py
> +from pydantic_settings import BaseSettings, SettingsConfigDict
Como lo hablamos con Erika en reunión, me parecio una forma mas limpia y optima de imporar variables de ambiente, además de que ayuda con el tipado de estas variables.

2024-06-06 22:49 UTC, cazapatamar commented on README.md
> +    - -o --overwrite # Sobrescribe una colección ya existente (opcional)
Vale, entiendo. Desde que la opción por defecto sea que la colección se sobreescriba me parece que está bien.

2024-06-07 23:24 UTC, erikasv requested changes
Lamento la demora en la revisión, hay algunos errores que se deberían capturar y creo que hay cosas que se pueden mejorar en el código.

En cuanto a la funcionalidad la veo bien, solo faltaría borrar los archivos cog cuando se borra la colección.

2024-06-07 23:24 UTC, erikasv commented on src/main.py
> +    output_dir = f"output/{collection_name}"
el parámetro del nombre de la colección es opcional

2024-06-07 23:24 UTC, erikasv commented on src/utils/raster.py
> +        gdal.Translate(
En algún intento la versión del paquete de gdal no conocía el formato COG y en consola se mostraba el error `ERROR 5: Output driver `COG' not recognised.`, pero la ejecución continuó hasta que falló porque buscaba el archivo en la carpeta `output`

La versión del paquete era la 3.0.2 instalada desde conda-forge

2024-06-07 23:24 UTC, erikasv commented on src/collection.py
> +            self.items[i]["final_file"] = raster.tif_to_cog(
Aquí se está capturando la ruta completa al cog, pero el atributo `final_file` en cada item no se está usando para nada después.

Me parece confuso que en la función `upload_layers` se use el atributo `input_file` y se construya la ruta dentro de la función, creo que la función `upload_file` del `storage` debería recibir la ruta completa, y si ya se está capturando este "final_file" usarlo mejor, de lo contrario no capturar este valor y armar la ruta desde acá y no dentro de `storage.upload_file`

2024-06-07 23:24 UTC, erikasv commented on src/utils/storage.py
> +def upload_file(abs_config, folder_path, file_name):
ya entendí a qué se refería Camilo con el tema de los settings, no sé si la inyección a esta función aporte algo la verdad, creo que sería mejor que los settings los lea este archivo y use los que necesite.

 @cazapatamar qué crees que es mejor en este caso?

2024-06-07 23:24 UTC, erikasv commented on src/collection.py
> +    def remove_collection(self):
En esta función estaría faltando eliminar los archivos del blobstorage

2024-06-07 23:52 UTC, cazapatamar commented on src/utils/storage.py
> +def upload_file(abs_config, folder_path, file_name):
Tampoco me convence del todo pasar los settings de esta forma como atributo de la clase Collection. Esto nos podria conducir en el futuro a tener que tener este mismo comportamiento con todas las clases que creemos y no creo que sea lo mejor.

Sugiero hacer un import de settings en la clase `Collection` y no manejarlo como atributo en el constructor. Hacer que `upload_file` reciba 2 parametros tipo string (abs_string y abs_container) en vez del objeto completo settings. De esta forma solo se importaria una vez el objeto settings en la clase `Collection` y enviaría a los metodos de la clase solo los valores que necesitan. Tambien permitiría reutilizar mas fácilmente en el futuro el metodo `upload_file`.

2024-06-08 00:30 UTC, erikasv commented on src/utils/storage.py
> +def upload_file(abs_config, folder_path, file_name):
A mi igual no me parece que se le pasen como atributos a esta función, por qué no los puede importar el archivo directamente?

2024-06-18 22:21 UTC, ManuelStardust commented on src/utils/storage.py
> +def upload_file(abs_config, folder_path, file_name):
Se implemento la lecura de settings para ser leidos directamente por los archivos que los usan según la sugerencia

2024-06-19 15:04 UTC, ManuelStardust commented on src/utils/raster.py
> +        gdal.Translate(
Se agregó una forma de comprobar la existencia final del archivo convertido.

2024-06-19 16:02 UTC, erikasv requested changes

2024-06-19 16:02 UTC, erikasv commented on src/utils/storage.py
> +    # TODO: Considerar si este script deberia ser una clase
Creo que este archivo debería ser una clase. Porque en cada función (`upload_file` y `remove_file`) se está llamando a esta función `config`, entonces por ejemplo, cuando se están borrando  los archivos de los items de la colección que se está sobreescribiendo, por cada uno de ellos se crea el objeto `container_client` y eso debería ser un atributo de la clase

2024-06-19 16:03 UTC, erikasv commented on src/utils/storage.py
> +    # TODO: Considerar si este script deberia ser una clase
También creo que (aunque puede que no se use si se pasa el parámetro -v) se debería instanciar esa clase en el constructor de collection

2024-06-19 16:07 UTC, erikasv commented
Ejecuté el comando para que sobrescribiera una colección y me botó este error: `azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.`

2024-06-20 14:05 UTC, ManuelStardust commented
> Ejecuté el comando para que sobrescribiera una colección y me botó este error: `azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.`

Se agrego una validación para verificar la existencia del blob en azure.

2024-06-21 16:37 UTC, erikasv approved these changes

2024-06-21 17:08 UTC, merged