Create conda environment
PEM-Humboldt/stac-data-tools pull request #14
Opened 2024-09-23 17:21 UTC by cazapatamar

## 🛠️ Changes
- Create environment.yml and delete requirements.txt in order to use conda to manage dependencies
- Update Readme

## 📝 Associated issues
#13

2024-09-23 17:55 UTC, cazapatamar commented
Tested in Kubuntu and Windows 10

2024-09-23 23:12 UTC, erikasv reviewed
Tested on ubuntu 22.04 and mac ventura. :heavy_check_mark: 

Please @ManuelStardust or @denarch22 test and approve in case there are no issues

2024-09-24 14:44 UTC, ManuelStardust requested changes

2024-09-24 14:44 UTC, ManuelStardust commented on README.md
>  Para cargar una nueva colección (incluyendo los items de la misma) se debe seguir los siguientes pasos:
typo "deben"

2024-09-24 14:44 UTC, ManuelStardust commented on README.md
> +1. Crear una carpeta, sin importar su nombre o ubicación, donde se va a almacenar todos los archivos necesarios para cargar la colección al STAC.
typo "van"

2024-09-24 16:05 UTC, ManuelStardust commented
Tested in Debian 12 ✅

2024-09-24 16:05 UTC, ManuelStardust approved these changes
Everything works fine

2024-09-24 16:08 UTC, merged