Adjustment auth in commands
PEM-Humboldt/stac-data-tools pull request #22
Opened 2024-11-27 20:47 UTC by denarch22

## 🛠️ Changes
The adjustment is made to add the authentication commands such as user and password, internally accessing the generated token and making the request to the server

## 📝 Associated issues
[Agregar protección a endpoints post, put y delete](https://github.com/PEM-Humboldt/stac-fastapi/issues/2)

2024-11-27 22:57 UTC, erikasv requested changes

2024-11-27 22:57 UTC, erikasv commented on README.md
> +
la autenticación debe configurarse en el archivo de las variables de ambiente (es demasiado tedioso tener que pasar estos atributos a todos los comandos)

2024-11-27 22:57 UTC, erikasv commented on src/config.py
> +    auth_url: str
No hay explicación de para qué es esta variable, ni instrucciones para configurarla

2024-11-27 22:57 UTC, erikasv commented on src/main.py
> +from pypgstac.db import settings
esto no se está usando

2024-11-27 22:57 UTC, erikasv commented on src/main.py
> +        "-f", "--folder", required=True, help="Input folder"
por qué eliminaste el atributo `dest`?

por qué le cambiaste el nombre a la ayuda?

2024-11-27 22:57 UTC, erikasv commented on src/main.py
No entiendo por qué en todos los argumentos cambiaste la descripción de la ayuda y eliminaste el atributo `dest`, ni por qué cambiaste las descripciones de los comandos

2024-11-27 22:57 UTC, erikasv commented on src/test.py
cuál es el propósito de este archivo?

2024-11-27 22:57 UTC, erikasv commented on src/main.py
> +        logger.info("Error en los argumentos:", e)
este catch debe hacerse justo después de obtener el token, no es necesario encerrar todo dentro del try.

El mensaje es completamente erroneo, solo puede salirse por un error de autenticación

2024-11-27 22:57 UTC, erikasv commented on src/utils/auth.py
> +def authenticate(username, password, stac_url, auth_url):
ninguna de estos argumentos debería ser un argumento, todo debería leerse de la configuración

2024-11-27 22:57 UTC, erikasv commented on src/utils/stac_rest.py
> +        # Si el POST falla con 409, intenta con PUT
eliminar comentario

2024-11-27 22:57 UTC, erikasv commented on src/utils/stac_rest.py
> +        print(f"Error during post or put: {e}")
por qué este cambio?

2024-11-27 22:57 UTC, erikasv commented on src/utils/stac_rest.py
> +    print(response)
eliminar print

2024-11-27 22:57 UTC, erikasv commented on src/utils/stac_rest.py
> +    print(response)
eliminar

2024-11-29 00:02 UTC, denarch22 commented on src/main.py
> +        "-f", "--folder", required=True, help="Input folder"
Estaba realizando algunas pruebas con los help, pero no fue por algún motivo especial

2024-12-04 17:43 UTC, erikasv requested changes

2024-12-04 17:43 UTC, erikasv commented on README.md
> +python src/main.py create -f folder_name [-c collection_name]
por qué borraste la opción `-o`? de hecho falta documentarla

2024-12-04 17:43 UTC, erikasv commented on src/main.py
> +        sysexit(e)
este except no está haciendo nada, todo el `try` es innecesario

2024-12-04 17:43 UTC, erikasv commented on src/main.py
> +            logger.info("Collection uploaded successfully.")
Por qué agrupaste las dos cosas bajo el mismo log?

2024-12-04 17:43 UTC, erikasv commented on src/main.py
> -        sysexit("Process completed successfully.")
por que quitaste esta salida?

2024-12-04 17:43 UTC, erikasv commented on src/main.py
> +            input_folder = f"input/{args.folder}"
en este comando esta variable no se necesita más que para el llamado a `create_collection_local` así que no le veo sentido a crearla

2024-12-04 17:43 UTC, erikasv commented on src/utils/auth.py
> +        response = requests.post(f"{stac_url}{auth_url}", data=auth_data)
Es mejor tener el `/`, pero el servidor del STAC es sensible a los duplicados, entonces lo mejor es tener un constructor de url como el que tenemos en el [backend](https://github.com/PEM-Humboldt/biotablero-search-backend/blob/develop/app/utils/url.py)

2024-12-04 21:16 UTC, denarch22 commented on src/utils/auth.py
> +        response = requests.post(f"{stac_url}{auth_url}", data=auth_data)
ya agregue un archivo en util para usar la opcion

2024-12-04 21:17 UTC, denarch22 commented on src/main.py
> +            logger.info("Collection uploaded successfully.")
tan raro esto ya lo había corregido, igualmente en la corrección del try ya debería visualizarse

2024-12-04 21:18 UTC, denarch22 commented on README.md
> +python src/main.py create -f folder_name [-c collection_name]
ya lo agregue y documente, efectivamente esa documentación no estaba

2024-12-04 21:18 UTC, denarch22 commented on src/main.py
> -        sysexit("Process completed successfully.")
ya lo agregue, en los ajustes puede que lo haya borrado

2024-12-04 21:41 UTC, erikasv commented on src/main.py
> -        logger.info("Layers uploaded successfully.")
por qué borraste este log?

2024-12-04 21:41 UTC, erikasv commented on src/main.py
> +        logger.info("Validation successful.")
por qué cambiaste este exit por un log?

2024-12-04 21:41 UTC, erikasv commented on src/main.py
> +        logger.info("Collection removed successfully.")
Pending

por qué cambiaste este exit por un log?

2024-12-05 16:35 UTC, denarch22 commented on src/main.py
> +        logger.info("Collection removed successfully.")
según la conversación indicada, ya restaure los sysexit

2024-12-05 16:35 UTC, denarch22 commented on src/main.py
> +        logger.info("Validation successful.")
según la conversación indicada, ya restaure los sysexit

2024-12-05 16:48 UTC, denarch22 commented on src/main.py
> -        logger.info("Layers uploaded successfully.")
ya lo ajuste nuevamente, puede que se me haya borrado durante las pruebas

2024-12-06 15:31 UTC, erikasv commented
Por ahora veo todo bien, pero voy a esperar a que mezclemos en stac-fastapi para verificar todo en conjunto

2024-12-09 23:24 UTC, erikasv requested changes
Conceptualmente está bien, pero la implementación la encuentro muy enredada.

Por un lado me parece confuso que una función llamada `handle_http_error` reintente la petición a través de un parámetro que me da la impresión genera una recursividad (o potencialmente lo hace). Creo que no es necesario tener un archivo y una función extra para esto, sino que cada función que requiera autenticarse debería capturar el error y refrescar el token y reintentarlo si es necesario.

Pero entiendo que es mucha lógica que repetir y al ver lo enredado que se vuelve esta necesidad (tener que refrescar el token), tal vez sería mejor que el token no sea una propiedad de la colección, sino una variable de ambiente (que se setea a través del código) y que sean las funciones de `stac_rest` las que se encarguen de reintentar las peticiones si es por vencimiento del token. Así adicionalmente separamos la lógica de un servidor bajo stac y la autenticación que es algo extra, pero no sé si haya alguna desventaja de tomar este enfoque. @denarch22 @cazapatamar @ManuelStardust me gustaría saber su opinión.

2024-12-09 23:24 UTC, erikasv commented on env.sample
> +PASSWORD:""
usar `=`, no  `:`

2024-12-09 23:24 UTC, erikasv commented on src/config.py
> +    password_auth: str = "admin"
los nombres de estas variables no coinciden con los descritos para su configuración

2024-12-09 23:24 UTC, erikasv commented on src/config.py
> +    auth_url: str = ""
asigna el valor por defecto a la ruta que colocas en el readme, las posibilidades de que esta cambie son muy bajas

2024-12-09 23:24 UTC, erikasv commented on src/utils/auth.py
> +                    error_detail = error_response.get("detail", str(http_err))
Cuál es el beneficio de todo este desglose?, me parece que solo con lo que está en la línea 57 basta (así como estaba antes)

2024-12-09 23:24 UTC, erikasv commented on env.sample
> +PASSWORD:""
@denarch22 este cambio no se hizo, además las variables no coinciden con las descritas en el readme y en la configuración

2024-12-09 23:24 UTC, erikasv commented on src/config.py
> +    auth_url: str = ""
@denarch22 este cambio tampoco se hizo

2024-12-09 23:59 UTC, denarch22 commented on src/utils/auth.py
> +                    error_detail = error_response.get("detail", str(http_err))
Es que estaba revisando que trajera ambos campos ya que con este realice la verificación para el tema del error del token expirado, pero para el resto de casos puede funcionar solo el detalle

2024-12-10 00:47 UTC, denarch22 commented
> Por un lado me parece confuso que una función llamada `handle_http_error` reintente la petición a través de un parámetro que me da la impresión genera una recursividad (o potencialmente lo hace). Creo que no es necesario tener un archivo y una función extra para esto, sino que cada función que requiera autenticarse debería capturar el error y refrescar el token y reintentarlo si es necesario.
> 
> Pero entiendo que es mucha lógica que repetir y al ver lo enredado que se vuelve esta necesidad (tener que refrescar el token), tal vez sería mejor que el token no sea una propiedad de la colección, sino una variable de ambiente (que se setea a través del código) y que sean las funciones de `stac_rest` las que se encarguen de reintentar las peticiones si es por vencimiento del token. Así adicionalmente separamos la lógica de un servidor bajo stac y la autenticación que es algo extra, pero no sé si haya alguna desventaja de tomar este enfoque.


Según lo comentado por Erika me puso a pensar en las 2 opciones, por lo que hice este cuadro como indicando las ventajas y desventajas en cada caso:

![image](https://github.com/user-attachments/assets/0be2f9a8-8741-435a-9653-a123b5efeb4f)

En conclusión si se busca centralización y facilidad de mantenimiento la opción 2 seria la indicada, Si se busca mayor flexibilidad y personalización seria la opción 1 ,pero hay que considerar que se tendrá que manejar la autenticación en cada punto del negocio.

Igualmente quedo abierta a cualquier opinión.

2024-12-11 17:09 UTC, erikasv requested changes
La implementación realizada no guardar el tokkn como variable de ambiente sino en la variable settings de auth, pero esta variable no está pensada como un atributo de clase (ni siquiera hay una clase auth)

Lo correcto es escribir el token en variable de ambiente, de manera que siempre que se llame a getSettings (sin tener que pasar por auth) se tenga la versión más nueva del token.

2024-12-11 17:09 UTC, erikasv commented on src/main.py
> +from utils.auth import settings
no importar settings de auth sino de config y hacer el llamado a getSttings

2024-12-11 17:09 UTC, erikasv commented on src/utils/stac_rest.py
> +from utils.auth import authenticate, settings
settings no se debe importar de auth

2024-12-11 17:09 UTC, erikasv commented on src/utils/stac_rest.py
> +        url,
deshacer este cambio

2024-12-11 17:09 UTC, erikasv commented on src/collection.py
> +        self.token = token
token no se debe manejar como un atributo de Collection, nunca se va a actualizar y una vez se venza se va a reautenticar por cada nueva petición, en lugar de las mínimas necesarias.

2024-12-11 17:09 UTC, erikasv commented on src/collection.py
> +        self.headers = {"Authorization": f"Bearer {self.token}"}
este header se debe construir directamente en stac_rest tomando el valor de la variable ambiente token (directamente llamando a getSettings, sin pasar por auth)

2024-12-11 19:14 UTC, denarch22 commented on src/collection.py
> +        self.headers = {"Authorization": f"Bearer {self.token}"}
a listo , es que me había confundido con el tema de la autenticación de el usuario y password en la parte de la colección , pero ya entendí el flujo

2024-12-12 20:33 UTC, erikasv requested changes

2024-12-12 20:33 UTC, erikasv commented on src/utils/auth.py
> +            settings.token = new_token
En la revisión anterior y en la discusiones del flujo mencioné varias veces que token debería guardarse como variable de ambiente.

Esta implementación funciona ya que Settings es un singleton, y me parece mejor, pero esto no es transparente para los otros desarrolladores, entonces hay que definir la función set_token dentro de settings y hacer uso de ella acá

2024-12-12 20:33 UTC, erikasv commented on src/utils/stac_rest.py
> +        if response.status_code == 401:
Cambia el orden de estos if, así si primero ocurre el error de token vencido se capturará también el 409. (aunque estoy dudando si ese if del 409 está haciendo algo, pero es tema de otra tarea)

2024-12-12 20:33 UTC, erikasv commented on src/utils/stac_rest.py
> +    elif response.status_code == 401:
acá también hay que poner este if de primero

2024-12-13 01:18 UTC, denarch22 commented on src/utils/auth.py
> +            settings.token = new_token
ok, entiendo

2024-12-13 17:13 UTC, erikasv approved these changes

2024-12-13 17:51 UTC, merged