Add spec and example for new collections
PEM-Humboldt/stac-data-tools pull request #3
Opened 2024-03-06 23:51 UTC by erikasv

## 🛠️ Changes
- New specification for describing new collections
- Example of a collection description

## 📝 Associated issues
#1

2024-03-08 21:35 UTC, ManuelStardust requested changes

2024-03-08 21:35 UTC, ManuelStardust commented on collection.example.json
> +  "tite": "Time series of the binary presence of forests in Colombia",
typo

2024-03-08 22:45 UTC, ManuelStardust approved these changes

2024-03-11 14:45 UTC, cazapatamar requested changes

2024-03-11 14:45 UTC, cazapatamar commented on collection_spec.md
> +| _metadata.properties_ | object | objeto que relaciona tuplas de información con los valores de los items. | No | Todos los atributos de este objeto son arrelgos y __deben tener la misma cantidad de
Typo "arreglos"

2024-03-12 14:05 UTC, cazapatamar approved these changes

2024-04-01 22:18 UTC, merged